[package]
name = "alt-life"
version = "0.1.0"
authors = ["Kazzix <kazzix14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ezui = {git = "https://github.com/kazzix14/ezui.git", branch = "develop"}
